"""add training_plans

Revision ID: f28269b48e52
Revises: 441fe38b42d3
Create Date: 2026-03-22 11:44:30.109283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f28269b48e52'
down_revision: Union[str, Sequence[str], None] = '441fe38b42d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('days_per_week', sa.Integer(), nullable=False),
    sa.Column('days', sa.JSON(), nullable=False),
    sa.Column('methodology_notes', sa.Text(), nullable=True),
    sa.Column('warnings', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('constraints', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), server_default='chat', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('parent_plan_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_plan_id'], ['training_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: checkpoint_* tables are managed by LangGraph, not Alembic
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('training_plans')
